#version 330 core
#extension GL_ARB_compute_shader : require
#extension GL_ARB_shader_image_load_store : require
#extension GL_ARB_shading_language_420pack : enable

layout(local_size_x = 1, local_size_y = 1) in;
layout(rgba32f, binding = 0) uniform image2D surface;

void main() {
    vec4 pixel = vec4(1.0, 0.0, 0.0, 1.0);
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    imageStore(surface, coords, pixel);
}
